apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: example-grafana
  namespace: grafana
spec:
  config:
    auth:
      disable_signout_menu: true
    auth.anonymous:
      enabled: false
    log:
      level: warn
      mode: console
    security:
      admin_password: secret
      admin_user: jgw
  dashboardLabelSelector:
  - matchExpressions:
    - key: app
      operator: In
      values:
      - grafana
  ingress:
    enabled: true
    hostname: HOSTNAME # hostname.apps.cvogt-22.devcluster.openshift.com

