# permissions for end users to edit calculators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: calculator-editor-role
rules:
- apiGroups:
  - math.com
  resources:
  - calculators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - math.com
  resources:
  - calculators/status
  verbs:
  - get
